name: 'Bump Package Version'
on:
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version using labels
        id: version-bump
        uses: apomalyn/bump-version-using-labels@v1.5.0
        with:
          file_path: 'package.json'
      
      - name: Create tag
        if: ${{ steps.version-bump.outputs.has_changed == 'true' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if the tag already exists
          if ! git rev-parse "v${{ steps.version-bump.outputs.version }}" >/dev/null 2>&1; then
            git tag v${{ steps.version-bump.outputs.version }}
            git push origin v${{ steps.version-bump.outputs.version }}
            echo "Tag v${{ steps.version-bump.outputs.version }} created and pushed"
          else
            echo "Tag v${{ steps.version-bump.outputs.version }} already exists, skipping tag creation"
          fi
